-- grant create table to cinema_admin;
-- grant create sequence to cinema_admin;
create table cinema
(
    id number generated by default as identity primary key,
    name nvarchar2(30) not null,
    address nvarchar2(100) not null
)
tablespace TS_CINEMA;

create table cinema_hall
(
    id number generated by default as identity primary key,
    cinema_id number not null,
    rows_count number not null,
    places_count number not null,
    constraint fk_cinhall
        foreign key (cinema_id) references cinema(id)
)
tablespace TS_CINEMA;

create table movie
(
    id number generated by default as identity primary key,
    title nvarchar2(50)
)
tablespace TS_CINEMA;

create table genre
(
    id number generated by default as identity primary key,
    name nvarchar2(20)
)
tablespace TS_CINEMA;

create table movie_genre
(
    movie_id number not null,
    genre_id number not null,
    constraint fk_movgenmovie
        foreign key (movie_id) references movie(id),
    constraint fk_movgengenre
        foreign key (genre_id) references genre(id)
)
tablespace TS_CINEMA;
    
create table seance
(
    id number generated by default as identity primary key,
    cinema_hall_id number not null,
    movie_id number not null,
    timetable date not null,
    constraint fk_seancinhall
        foreign key (cinema_hall_id) references cinema_hall(id),
    constraint fk_seanmovid
        foreign key (movie_id) references movie(id)
)
partition by range (timetable)
interval (NUMTOYMINTERVAL(3, 'MONTH'))
(
    partition seance_p1 values less than (TO_DATE('1-1-2000', 'DD-MM-YYYY')), 
    partition seance_p2 values less than (TO_DATE('1-1-2005', 'DD-MM-YYYY'))
)
tablespace TS_CINEMA;

create table place
(
    id number generated by default as identity primary key,
    roww number not null,
    place number not null,
    cost float not null,
    seance_id number not null,
    constraint fk_placeseanceid
        foreign key (seance_id) references seance(id)
)
tablespace TS_CINEMA;

create table customer
(
    id number generated by default as identity primary key,
    login nvarchar2(30) not null,
    password nvarchar2(30) not null,
    email varchar2(30) not null
)
tablespace TS_CINEMA;

create table booking
(
    id number generated by default as identity primary key,
    customer_id number not null,
    booking_date date not null,
    constraint fk_bookingcustid
        foreign key (customer_id) references customer(id)
)
tablespace TS_CINEMA;

create table booked_places
(   
    id number generated by default as identity primary key,
    place_id number not null,
    booking_id number not null,
    constraint fk_bookplaceplid
        foreign key (place_id) references place(id),
    constraint fk_bookplacebookid
        foreign key (booking_id) references booking(id)
)
tablespace TS_CINEMA;

drop table booked_places;
drop table booking;
drop table customer;
drop table place;
drop table seance;
drop table movie_genre;
drop table genre;
drop table movie;
drop table cinema_hall;
drop table cinema;
